on:
  workflow_call:
    secrets:
      CUSTOM_GITHUB_TOKEN:
        required: true

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo ${{ github.ref_name }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name:  ${{ github.ref_name }}
          generate_release_notes: true
          # we do a draft and then publish to allow us to trigger a github workflow from the event.
          # This might not even be necessary, Github Actions is fast moving and lots of examples are out of date.
          # This does work though :-)
          draft: true
      - name: Publish release
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
